<a href="https://colab.research.google.com/github/Gabrielcs96/Estudos-iniciais-em-Python/blob/main/1%C2%B0_C%C3%B3digo_de_Python_estudando_estat%C3%ADstica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Primeiro código em Python
Aqui eu fiz um código super extenso, testando a biblioteca Pandas e usando o "google.colab" para importar arquivos para dentro do Colab.

O Maior foco que eu tive aqui foi a criação de dataframes e o tratamento dos números, assim eu consegui entender bsaicamente como a biblioteca funciona e como eu faço operações com os dataframes.

Além disso eu usei também a Numpy para operar vetores e matrizes, entendendo como a biblioteca funciona e me tornando capaz de utilizar ela em situações reais;

por fim eu fiz algumas operações com números, como a linguagem é dinamicamente é tipada eu tentei algumas coisas para saber o que funciona e o que não aqui.


#Iniciando com o carregamento, tratamento e utilização de datasets


In [ ]:
 from google.colab import files
 from google.colab import drive
 import pandas as pd

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/PYTHON - E.B.A /Cópia de top10s.csv", encoding = "ISO-8859-1")

FileNotFoundError: ignored

In [ ]:
df.head()

Unnamed: 0                 title      artist        top genre  year  bpm  \
0           1      Hey, Soul Sister       Train       neo mellow  2010   97   
1           2  Love The Way You Lie      Eminem  detroit hip hop  2010   87   
2           3               TiK ToK       Kesha        dance pop  2010  120   
3           4           Bad Romance   Lady Gaga        dance pop  2010  119   
4           5  Just the Way You Are  Bruno Mars              pop  2010  109   

   nrgy  dnce  dB  live  val  dur  acous  spch  pop  
0    89    67  -4     8   80  217     19     4   83  
1    93    75  -5    52   64  263     24    23   82  
2    84    76  -3    29   71  200     10    14   80  
3    92    70  -4     8   71  295      0     4   79  
4    84    64  -5     9   43  221      2     4   78

In [ ]:
files.upload()

In [ ]:
dfs = pd.read_csv('SpotifyTopSongsByCountry - May 2020.csv')

In [ ]:
dfs.head()

Country Continent  Rank                            Title  \
0  Global    Global     1  Rain On Me (with Ariana Grande)   
1  Global    Global     2                  Blinding Lights   
2  Global    Global     3     ROCKSTAR (feat. Roddy Ricch)   
3  Global    Global     4            Roses - Imanbek Remix   
4  Global    Global     5                     Toosie Slide   

                    Artists                            Album  Explicit  \
0  Lady Gaga, Ariana Grande  Rain On Me (with Ariana Grande)         0   
1                The Weeknd                      After Hours         0   
2       DaBaby, Roddy Ricch                 BLAME IT ON BABY         1   
3        SAINt JHN, Imanbek            Roses (Imanbek Remix)         1   
4                     Drake             Dark Lane Demo Tapes         1   

  Duration  
0     3:02  
1     3:20  
2     3:01  
3     2:56  
4     4:07

#Entendendo as colunas do dataset:
Genre - the genre of the track

Year - the release year of the recording. Note that due to vagaries of releases, re-releases, re-issues and general madness, sometimes the release years are not what you'd expect.

Added - the earliest date you added the track to your collection.

Beats Per Minute (BPM) - The tempo of the song.

Energy - The energy of a song - the higher the value, the more energtic. song

Danceability - The higher the value, the easier it is to dance to this song.

Loudness (dB) - The higher the value, the louder the song.

Liveness - The higher the value, the more likely the song is a live recording.

Valence - The higher the value, the more positive mood for the song.


Length - The duration of the song.

Acousticness - The higher the value the more acoustic the song is.

Speechiness - The higher the value the more spoken word the song contains.

Popularity - The higher the value the more popular the song is.

Duration - The length of the song.

In [ ]:
df.tail()
#Mostrar as últimas linhas

Unnamed: 0                                              title  \
598         599                Find U Again (feat. Camila Cabello)   
599         600      Cross Me (feat. Chance the Rapper & PnB Rock)   
600         601  No Brainer (feat. Justin Bieber, Chance the Ra...   
601         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
602         603                                   Kills You Slowly   

               artist   top genre  year  bpm  nrgy  dnce  dB  live  val  dur  \
598       Mark Ronson   dance pop  2019  104    66    61  -7    20   16  176   
599        Ed Sheeran         pop  2019   95    79    75  -6     7   61  206   
600         DJ Khaled   dance pop  2019  136    76    53  -5     9   65  260   
601       Mark Ronson   dance pop  2019  114    79    60  -6    42   24  217   
602  The Chainsmokers  electropop  2019  150    44    70  -9    13   23  213   

     acous  spch  pop  
598      1     3   75  
599     21    12   75  
600      7    34   70  
601      1     7   69  
602      6     6   67

In [ ]:
df.info()
#Trazer informações do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 603 entries, 0 to 602
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  603 non-null    int64 
 1   title       603 non-null    object
 2   artist      603 non-null    object
 3   top genre   603 non-null    object
 4   year        603 non-null    int64 
 5   bpm         603 non-null    int64 
 6   nrgy        603 non-null    int64 
 7   dnce        603 non-null    int64 
 8   dB          603 non-null    int64 
 9   live        603 non-null    int64 
 10  val         603 non-null    int64 
 11  dur         603 non-null    int64 
 12  acous       603 non-null    int64 
 13  spch        603 non-null    int64 
 14  pop         603 non-null    int64 
dtypes: int64(12), object(3)
memory usage: 70.8+ KB


In [ ]:
df.dtypes

Unnamed: 0     int64
title         object
artist        object
top genre     object
year           int64
bpm            int64
nrgy           int64
dnce           int64
dB             int64
live           int64
val            int64
dur            int64
acous          int64
spch           int64
pop            int64
dtype: object

In [ ]:
df.select_dtypes(include='int64')

Unnamed: 0  year  bpm  nrgy  dnce  dB  live  val  dur  acous  spch  pop
0             1  2010   97    89    67  -4     8   80  217     19     4   83
1             2  2010   87    93    75  -5    52   64  263     24    23   82
2             3  2010  120    84    76  -3    29   71  200     10    14   80
3             4  2010  119    92    70  -4     8   71  295      0     4   79
4             5  2010  109    84    64  -5     9   43  221      2     4   78
..          ...   ...  ...   ...   ...  ..   ...  ...  ...    ...   ...  ...
598         599  2019  104    66    61  -7    20   16  176      1     3   75
599         600  2019   95    79    75  -6     7   61  206     21    12   75
600         601  2019  136    76    53  -5     9   65  260      7    34   70
601         602  2019  114    79    60  -6    42   24  217      1     7   69
602         603  2019  150    44    70  -9    13   23  213      6     6   67

[603 rows x 12 columns]

In [ ]:
df.select_dtypes(include='object')

title            artist  \
0                                     Hey, Soul Sister             Train   
1                                 Love The Way You Lie            Eminem   
2                                              TiK ToK             Kesha   
3                                          Bad Romance         Lady Gaga   
4                                 Just the Way You Are        Bruno Mars   
..                                                 ...               ...   
598                Find U Again (feat. Camila Cabello)       Mark Ronson   
599      Cross Me (feat. Chance the Rapper & PnB Rock)        Ed Sheeran   
600  No Brainer (feat. Justin Bieber, Chance the Ra...         DJ Khaled   
601    Nothing Breaks Like a Heart (feat. Miley Cyrus)       Mark Ronson   
602                                   Kills You Slowly  The Chainsmokers   

           top genre  
0         neo mellow  
1    detroit hip hop  
2          dance pop  
3          dance pop  
4                pop  
..               ...  
598        dance pop  
599              pop  
600        dance pop  
601        dance pop  
602       electropop  

[603 rows x 3 columns]

In [ ]:
df.describe()

Unnamed: 0         year         bpm        nrgy        dnce  \
count  603.000000   603.000000  603.000000  603.000000  603.000000   
mean   302.000000  2014.592040  118.545605   70.504146   64.379768   
std    174.215384     2.607057   24.795358   16.310664   13.378718   
min      1.000000  2010.000000    0.000000    0.000000    0.000000   
25%    151.500000  2013.000000  100.000000   61.000000   57.000000   
50%    302.000000  2015.000000  120.000000   74.000000   66.000000   
75%    452.500000  2017.000000  129.000000   82.000000   73.000000   
max    603.000000  2019.000000  206.000000   98.000000   97.000000   

               dB        live         val         dur       acous        spch  \
count  603.000000  603.000000  603.000000  603.000000  603.000000  603.000000   
mean    -5.578773   17.774461   52.225539  224.674959   14.326700    8.358209   
std      2.798020   13.102543   22.513020   34.130059   20.766165    7.483162   
min    -60.000000    0.000000    0.000000  134.000000    0.000000    0.000000   
25%     -6.000000    9.000000   35.000000  202.000000    2.000000    4.000000   
50%     -5.000000   12.000000   52.000000  221.000000    6.000000    5.000000   
75%     -4.000000   24.000000   69.000000  239.500000   17.000000    9.000000   
max     -2.000000   74.000000   98.000000  424.000000   99.000000   48.000000   

              pop  
count  603.000000  
mean    66.520730  
std     14.517746  
min      0.000000  
25%     60.000000  
50%     69.000000  
75%     76.000000  
max     99.000000

In [ ]:
df.isna().sum()
#Saber quantas casas são nulas dentro do Data Frame

Unnamed: 0    0
title         0
artist        0
top genre     0
year          0
bpm           0
nrgy          0
dnce          0
dB            0
live          0
val           0
dur           0
acous         0
spch          0
pop           0
dtype: int64

In [ ]:
df['title']
#VBai mostra apenas as os títulos, ou seja... o noem dos títulos das músicas, porque eu selecionei o " null"

0                                       Hey, Soul Sister
1                                   Love The Way You Lie
2                                                TiK ToK
3                                            Bad Romance
4                                   Just the Way You Are
                             ...                        
598                  Find U Again (feat. Camila Cabello)
599        Cross Me (feat. Chance the Rapper & PnB Rock)
600    No Brainer (feat. Justin Bieber, Chance the Ra...
601      Nothing Breaks Like a Heart (feat. Miley Cyrus)
602                                     Kills You Slowly
Name: title, Length: 603, dtype: object

In [ ]:
df['artist'].unique()
#trazer as questões sem repetições por conta do "unique"

array(['Train', 'Eminem', 'Kesha', 'Lady Gaga', 'Bruno Mars',
       'Justin Bieber', 'Taio Cruz', 'OneRepublic', 'Alicia Keys',
       'Rihanna', 'Flo Rida', 'Mike Posner', 'Far East Movement', 'Usher',
       'Sean Kingston', 'The Black Eyed Peas', 'Adam Lambert', 'Maroon 5',
       'Neon Trees', 'Selena Gomez & The Scene', 'Enrique Iglesias',
       'Katy Perry', 'Britney Spears', '3OH!3', 'David Guetta',
       'Christina Aguilera', 'Florence + The Machine', 'Shakira',
       'Tinie Tempah', 'T.I.', 'Martin Solveig', 'Christina Perri',
       'Adele', 'Pitbull', 'Beyoncé', 'Hot Chelle Rae', 'Avril Lavigne',
       'Kanye West', 'LMFAO', 'Jessie J', 'Jennifer Lopez', 'Chris Brown',
       'Sleeping At Last', 'Nicki Minaj', 'P!nk', 'Coldplay',
       'One Direction', 'Taylor Swift', 'Carly Rae Jepsen',
       'Kelly Clarkson', 'Owl City', 'The Wanted', 'fun.',
       'Ellie Goulding', 'Gym Class Heroes', 'Avicii', 'The Script',
       'Miley Cyrus', 'Swedish House Mafia', 'Daft Punk'

In [ ]:
df['artist'].nunique()
# Contar a quantidade de " artistas diferentes" que tem na playlist

184

In [ ]:
df.shape
#mostrar a quantidade de linhas por colunas

(603, 15)

In [ ]:
df.size
#Mostrar a quantidade de "quadradinhos" ( células) totais.

9045

In [ ]:
df.columns
#Traz todas as colunas

Index(['Unnamed: 0', 'title', 'artist', 'top genre', 'year', 'bpm', 'nrgy',
       'dnce', 'dB', 'live', 'val', 'dur', 'acous', 'spch', 'pop'],
      dtype='object')

In [ ]:
df.memory_usage()
#Descobrir o tamanho que cada coisinha está tomando na tabela

Index          128
Unnamed: 0    4824
title         4824
artist        4824
top genre     4824
year          4824
bpm           4824
nrgy          4824
dnce          4824
dB            4824
live          4824
val           4824
dur           4824
acous         4824
spch          4824
pop           4824
dtype: int64

In [ ]:
df.nsmallest(5,'nrgy')


Unnamed: 0                          title             artist  \
442         443              Million Years Ago              Adele   
431         432                          Start        John Legend   
255         256               Not About Angels              Birdy   
249         250                  Say Something  A Great Big World   
436         437  Beautiful Birds (feat. Birdy)          Passenger   

        top genre  year  bpm  nrgy  dnce  dB  live  val  dur  acous  spch  pop  
442  british soul  2016    0     0     0 -60     0    0  227      0     0    0  
431    neo mellow  2016  110     4    52 -15     9   26  310     99     4   47  
255    neo mellow  2014  116    14    41 -10     9   23  190     97     4   56  
249    neo mellow  2014  138    15    45  -9     9    9  229     87     3   61  
436      folk-pop  2016   86    17    39 -13    11   14  214     91     3   36

In [ ]:
df.nlargest(5,'nrgy')

Unnamed: 0                             title          artist  \
50           51                             Hello  Martin Solveig   
198         199                          Pom Poms  Jonas Brothers   
134         135  Don't Stop the Party (feat. TJR)         Pitbull   
181         182                       Rock N Roll   Avril Lavigne   
24           25               All The Right Moves     OneRepublic   

        top genre  year  bpm  nrgy  dnce  dB  live  val  dur  acous  spch  pop  
50       big room  2010  128    98    67  -3    10   45  191      1     3    0  
198      boy band  2013  148    98    68  -2    28   90  198      7     9   52  
134     dance pop  2012  127    96    72  -4    38   95  206      1     9   59  
181  canadian pop  2013  184    96    47  -3    34   67  207      1    13   61  
24      dance pop  2010  146    95    53  -4    28   65  238     26     5   65

In [ ]:
df_ops=df.drop_duplicates(subset='title', keep='last')
#copiando os dados de "df" para o " Df_ops" e excluindo duplicadas do "title" onde eu mantenho apenas o que chegou " por último"

In [ ]:
display(df_ops)

Unnamed: 0                                              title  \
0             1                                   Hey, Soul Sister   
1             2                               Love The Way You Lie   
2             3                                            TiK ToK   
3             4                                        Bad Romance   
5             6                                               Baby   
..          ...                                                ...   
598         599                Find U Again (feat. Camila Cabello)   
599         600      Cross Me (feat. Chance the Rapper & PnB Rock)   
600         601  No Brainer (feat. Justin Bieber, Chance the Ra...   
601         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
602         603                                   Kills You Slowly   

               artist        top genre  year  bpm  nrgy  dnce  dB  live  val  \
0               Train       neo mellow  2010   97    89    67  -4     8   80   
1              Eminem  detroit hip hop  2010   87    93    75  -5    52   64   
2               Kesha        dance pop  2010  120    84    76  -3    29   71   
3           Lady Gaga        dance pop  2010  119    92    70  -4     8   71   
5       Justin Bieber     canadian pop  2010   65    86    73  -5    11   54   
..                ...              ...   ...  ...   ...   ...  ..   ...  ...   
598       Mark Ronson        dance pop  2019  104    66    61  -7    20   16   
599        Ed Sheeran              pop  2019   95    79    75  -6     7   61   
600         DJ Khaled        dance pop  2019  136    76    53  -5     9   65   
601       Mark Ronson        dance pop  2019  114    79    60  -6    42   24   
602  The Chainsmokers       electropop  2019  150    44    70  -9    13   23   

     dur  acous  spch  pop  
0    217     19     4   83  
1    263     24    23   82  
2    200     10    14   80  
3    295      0     4   79  
5    214      4    14   77  
..   ...    ...   ...  ...  
598  176      1     3   75  
599  206     21    12   75  
600  260      7    34   70  
601  217      1     7   69  
602  213      6     6   67  

[584 rows x 15 columns]

In [ ]:
df_ops

Unnamed: 0                                              title  \
0             1                                   Hey, Soul Sister   
1             2                               Love The Way You Lie   
2             3                                            TiK ToK   
3             4                                        Bad Romance   
5             6                                               Baby   
..          ...                                                ...   
598         599                Find U Again (feat. Camila Cabello)   
599         600      Cross Me (feat. Chance the Rapper & PnB Rock)   
600         601  No Brainer (feat. Justin Bieber, Chance the Ra...   
601         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
602         603                                   Kills You Slowly   

               artist        top genre  year  bpm  nrgy  dnce  dB  live  val  \
0               Train       neo mellow  2010   97    89    67  -4     8   80   
1              Eminem  detroit hip hop  2010   87    93    75  -5    52   64   
2               Kesha        dance pop  2010  120    84    76  -3    29   71   
3           Lady Gaga        dance pop  2010  119    92    70  -4     8   71   
5       Justin Bieber     canadian pop  2010   65    86    73  -5    11   54   
..                ...              ...   ...  ...   ...   ...  ..   ...  ...   
598       Mark Ronson        dance pop  2019  104    66    61  -7    20   16   
599        Ed Sheeran              pop  2019   95    79    75  -6     7   61   
600         DJ Khaled        dance pop  2019  136    76    53  -5     9   65   
601       Mark Ronson        dance pop  2019  114    79    60  -6    42   24   
602  The Chainsmokers       electropop  2019  150    44    70  -9    13   23   

     dur  acous  spch  pop  
0    217     19     4   83  
1    263     24    23   82  
2    200     10    14   80  
3    295      0     4   79  
5    214      4    14   77  
..   ...    ...   ...  ...  
598  176      1     3   75  
599  206     21    12   75  
600  260      7    34   70  
601  217      1     7   69  
602  213      6     6   67  

[584 rows x 15 columns]

In [ ]:
df_ops.fillna(0)
# preenchendo todos os campos nulos como " 0"

Unnamed: 0                                              title  \
0             1                                   Hey, Soul Sister   
1             2                               Love The Way You Lie   
2             3                                            TiK ToK   
3             4                                        Bad Romance   
5             6                                               Baby   
..          ...                                                ...   
598         599                Find U Again (feat. Camila Cabello)   
599         600      Cross Me (feat. Chance the Rapper & PnB Rock)   
600         601  No Brainer (feat. Justin Bieber, Chance the Ra...   
601         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
602         603                                   Kills You Slowly   

               artist        top genre  year  bpm  nrgy  dnce  dB  live  val  \
0               Train       neo mellow  2010   97    89    67  -4     8   80   
1              Eminem  detroit hip hop  2010   87    93    75  -5    52   64   
2               Kesha        dance pop  2010  120    84    76  -3    29   71   
3           Lady Gaga        dance pop  2010  119    92    70  -4     8   71   
5       Justin Bieber     canadian pop  2010   65    86    73  -5    11   54   
..                ...              ...   ...  ...   ...   ...  ..   ...  ...   
598       Mark Ronson        dance pop  2019  104    66    61  -7    20   16   
599        Ed Sheeran              pop  2019   95    79    75  -6     7   61   
600         DJ Khaled        dance pop  2019  136    76    53  -5     9   65   
601       Mark Ronson        dance pop  2019  114    79    60  -6    42   24   
602  The Chainsmokers       electropop  2019  150    44    70  -9    13   23   

     dur  acous  spch  pop  
0    217     19     4   83  
1    263     24    23   82  
2    200     10    14   80  
3    295      0     4   79  
5    214      4    14   77  
..   ...    ...   ...  ...  
598  176      1     3   75  
599  206     21    12   75  
600  260      7    34   70  
601  217      1     7   69  
602  213      6     6   67  

[584 rows x 15 columns]

In [ ]:
df_ops.T
#Transpondo todos os campos nulos

0                     1          2            3    \
Unnamed: 0                 1                     2          3            4   
title       Hey, Soul Sister  Love The Way You Lie    TiK ToK  Bad Romance   
artist                 Train                Eminem      Kesha    Lady Gaga   
top genre         neo mellow       detroit hip hop  dance pop    dance pop   
year                    2010                  2010       2010         2010   
bpm                       97                    87        120          119   
nrgy                      89                    93         84           92   
dnce                      67                    75         76           70   
dB                        -4                    -5         -3           -4   
live                       8                    52         29            8   
val                       80                    64         71           71   
dur                      217                   263        200          295   
acous                     19                    24         10            0   
spch                       4                    23         14            4   
pop                       83                    82         80           79   

                      5          6            7    \
Unnamed: 0              6          7            8   
title                Baby   Dynamite      Secrets   
artist      Justin Bieber  Taio Cruz  OneRepublic   
top genre    canadian pop  dance pop    dance pop   
year                 2010       2010         2010   
bpm                    65        120          148   
nrgy                   86         78           76   
dnce                   73         75           52   
dB                     -5         -4           -6   
live                   11          4           12   
val                    54         82           38   
dur                   214        203          225   
acous                   4          0            7   
spch                   14          9            4   
pop                    77         77           77   

                                                   8    \
Unnamed: 0                                           9   
title       Empire State of Mind (Part II) Broken Down   
artist                                     Alicia Keys   
top genre                                      hip pop   
year                                              2010   
bpm                                                 93   
nrgy                                                37   
dnce                                                48   
dB                                                  -8   
live                                                12   
val                                                 14   
dur                                                216   
acous                                               74   
spch                                                 3   
pop                                                 76   

                                 9    \
Unnamed: 0                        10   
title       Only Girl (In The World)   
artist                       Rihanna   
top genre              barbadian pop   
year                            2010   
bpm                              126   
nrgy                              72   
dnce                              79   
dB                                -4   
live                               7   
val                               61   
dur                              235   
acous                             13   
spch                               4   
pop                               73   

                                                  10   ...               593  \
Unnamed: 0                                         11  ...               594   
title       Club Can't Handle Me (feat. David Guetta)  ...     Call You Mine   
artist                                       Flo Rida  ...  The Chainsmokers   
top genre                            

In [ ]:
df_ops.sample(10)
#pegar 10 carinhas aletórios para testar a amostra


Unnamed: 0                                              title  \
345         346                                        Bloodstream   
268         269                                  Thinking out Loud   
60           61                                    Tonight Tonight   
490         491                                        Younger Now   
168         169  Let Me Love You (Until You Learn To Love Yours...   
579         580                                            Happier   
433         434                                             Higher   
102         103                                           Firework   
554         555                        What I Need (feat. Kehlani)   
239         240    A Little Party Never Killed Nobody (All We Got)   

               artist     top genre  year  bpm  nrgy  dnce  dB  live  val  \
345        Ed Sheeran           pop  2015   89    59    48  -6     6   27   
268        Ed Sheeran           pop  2015   79    45    78  -6    18   59   
60     Hot Chelle Rae     dance pop  2011  100    78    69  -5    16   81   
490       Miley Cyrus     dance pop  2017  122    87    55  -5    14   33   
168             Ne-Yo     dance pop  2013  125    68    66  -7    37   25   
579        Marshmello       brostep  2019  100    79    69  -3    17   67   
433  Carly Rae Jepsen  canadian pop  2016  114    87    65  -5    37   44   
102        Katy Perry     dance pop  2011  124    83    64  -5    11   65   
554     Hayley Kiyoko     dance pop  2018  104    79    63  -4    16   41   
239            Fergie     dance pop  2014  130    62    76  -6     9   52   

     dur  acous  spch  pop  
345  309     20     5   52  
268  282     47     3   84  
60   200      8    12   75  
490  249      0     6   62  
168  252     25     4   70  
579  214     19     5   90  
433  234      1     6   46  
102  228     14     5   25  
554  220      5     6   67  
239  241      1    18   65

#ENCONTRANDO VALORES ESPECÍFICOS NO DATAFRAME

In [ ]:
df.query("artist== 'Ariana Grande'")
# Ao usar o " .query e atribuir dentro da função o campo e o que se está sendo procurado, você consegue achar o resultado da sua pesqusa, como num " filtro " do Excel!

Unnamed: 0                 title         artist  top genre  year  bpm  \
171         172               The Way  Ariana Grande  dance pop  2013   82   
221         222               Problem  Ariana Grande  dance pop  2014  103   
287         288        Love Me Harder  Ariana Grande  dance pop  2015   99   
291         292            Break Free  Ariana Grande  dance pop  2015  130   
323         324                 Focus  Ariana Grande  dance pop  2015  100   
368         369              Into You  Ariana Grande  dance pop  2016  108   
381         382       Dangerous Woman  Ariana Grande  dance pop  2016  134   
451         452          Side To Side  Ariana Grande  dance pop  2017  159   
513         514  no tears left to cry  Ariana Grande  dance pop  2018  122   

     nrgy  dnce  dB  live  val  dur  acous  spch  pop  
171    88    65  -3     8   86  227     29    11   68  
221    81    66  -5    16   63  194      2    15   75  
287    71    47  -4     8   24  236      1     3   76  
291    70    69  -5    20   28  215      1     5   75  
323    88    67  -6    44   79  211     27    24   66  
368    73    62  -6    14   37  244      2    11   80  
381    60    66  -5    36   29  236      5     4   78  
451    74    65  -6    24   61  226      5    23   80  
513    71    70  -6    29   35  206      4     6   84

In [ ]:
df.query("artist== 'Katy Perry'")

Unnamed: 0                         title      artist  top genre  year  \
28           29                 Teenage Dream  Katy Perry  dance pop  2010   
29           30              California Gurls  Katy Perry  dance pop  2010   
77           78                          E.T.  Katy Perry  dance pop  2011   
101         102  Last Friday Night (T.G.I.F.)  Katy Perry  dance pop  2011   
102         103                      Firework  Katy Perry  dance pop  2011   
124         125                    Part Of Me  Katy Perry  dance pop  2012   
127         128                    Wide Awake  Katy Perry  dance pop  2012   
128         129         The One That Got Away  Katy Perry  dance pop  2012   
144         145                          Roar  Katy Perry  dance pop  2013   
216         217                    Dark Horse  Katy Perry  dance pop  2014   
237         238             This Is How We Do  Katy Perry  dance pop  2014   
242         243                      Birthday  Katy Perry  dance pop  2014   
357         358              Legendary Lovers  Katy Perry  dance pop  2015   
408         409                          Rise  Katy Perry  dance pop  2016   
468         469                   Swish Swish  Katy Perry  dance pop  2017   
469         470         Chained To The Rhythm  Katy Perry  dance pop  2017   
485         486                   Bon appétit  Katy Perry  dance pop  2017   

     bpm  nrgy  dnce  dB  live  val  dur  acous  spch  pop  
28   120    80    72  -5    13   59  228      2     4   63  
29   125    75    79  -4    18   40  235      0     5   62  
77   152    87    62  -5    37   76  230      2    18   66  
101  126    81    65  -4    67   72  231      0     4   27  
102  124    83    64  -5    11   65  228     14     5   25  
124  130    92    68  -5     7   77  216      0     4   71  
127  160    68    51  -5    39   57  221      7     4   68  
128  134    80    69  -4    16   88  227      0     4   67  
144  180    77    55  -5    35   46  224      0     4   78  
216  132    59    65  -6    17   35  216      0     5   78  
237   96    64    69  -6    15   80  204      2     5   66  
242  126    67    72  -5    11   84  215      9     7   65  
357  126    84    62  -5     8   39  224      2     8   41  
408  101    64    55  -6    11   44  203      5     5   66  
468  120    71    84  -5    10   57  243      2     4   73  
469  190    80    45  -5    20   47  238      8    17   72  
485  106    79    80  -6    22   52  228     13     6   68

In [ ]:
df.query('dur>200')

Unnamed: 0                                              title  \
0             1                                   Hey, Soul Sister   
1             2                               Love The Way You Lie   
3             4                                        Bad Romance   
4             5                               Just the Way You Are   
5             6                                               Baby   
..          ...                                                ...   
596         597    Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)   
599         600      Cross Me (feat. Chance the Rapper & PnB Rock)   
600         601  No Brainer (feat. Justin Bieber, Chance the Ra...   
601         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
602         603                                   Kills You Slowly   

               artist        top genre  year  bpm  nrgy  dnce  dB  live  val  \
0               Train       neo mellow  2010   97    89    67  -4     8   80   
1              Eminem  detroit hip hop  2010   87    93    75  -5    52   64   
3           Lady Gaga        dance pop  2010  119    92    70  -4     8   71   
4          Bruno Mars              pop  2010  109    84    64  -5     9   43   
5       Justin Bieber     canadian pop  2010   65    86    73  -5    11   54   
..                ...              ...   ...  ...   ...   ...  ..   ...  ...   
596          DJ Snake  electronic trap  2019   96    80    84  -4     6   62   
599        Ed Sheeran              pop  2019   95    79    75  -6     7   61   
600         DJ Khaled        dance pop  2019  136    76    53  -5     9   65   
601       Mark Ronson        dance pop  2019  114    79    60  -6    42   24   
602  The Chainsmokers       electropop  2019  150    44    70  -9    13   23   

     dur  acous  spch  pop  
0    217     19     4   83  
1    263     24    23   82  
3    295      0     4   79  
4    221      2     4   78  
5    214      4    14   77  
..   ...    ...   ...  ...  
596  213     16    23   77  
599  206     21    12   75  
600  260      7    34   70  
601  217      1     7   69  
602  213      6     6   67  

[466 rows x 15 columns]

In [ ]:
df.loc[df['artist'] == 'Ariana Grande']
#Tô executando a mesma coisa que eu fiz em cima, porém aqui usando a função " LOC"

Unnamed: 0                 title         artist  top genre  year  bpm  \
171         172               The Way  Ariana Grande  dance pop  2013   82   
221         222               Problem  Ariana Grande  dance pop  2014  103   
287         288        Love Me Harder  Ariana Grande  dance pop  2015   99   
291         292            Break Free  Ariana Grande  dance pop  2015  130   
323         324                 Focus  Ariana Grande  dance pop  2015  100   
368         369              Into You  Ariana Grande  dance pop  2016  108   
381         382       Dangerous Woman  Ariana Grande  dance pop  2016  134   
451         452          Side To Side  Ariana Grande  dance pop  2017  159   
513         514  no tears left to cry  Ariana Grande  dance pop  2018  122   

     nrgy  dnce  dB  live  val  dur  acous  spch  pop  
171    88    65  -3     8   86  227     29    11   68  
221    81    66  -5    16   63  194      2    15   75  
287    71    47  -4     8   24  236      1     3   76  
291    70    69  -5    20   28  215      1     5   75  
323    88    67  -6    44   79  211     27    24   66  
368    73    62  -6    14   37  244      2    11   80  
381    60    66  -5    36   29  236      5     4   78  
451    74    65  -6    24   61  226      5    23   80  
513    71    70  -6    29   35  206      4     6   84

In [ ]:
df.isin(['Ariana Grande','Katy Perry'])

Unnamed: 0  title  artist  top genre   year    bpm   nrgy   dnce     dB  \
0         False  False   False      False  False  False  False  False  False   
1         False  False   False      False  False  False  False  False  False   
2         False  False   False      False  False  False  False  False  False   
3         False  False   False      False  False  False  False  False  False   
4         False  False   False      False  False  False  False  False  False   
..          ...    ...     ...        ...    ...    ...    ...    ...    ...   
598       False  False   False      False  False  False  False  False  False   
599       False  False   False      False  False  False  False  False  False   
600       False  False   False      False  False  False  False  False  False   
601       False  False   False      False  False  False  False  False  False   
602       False  False   False      False  False  False  False  False  False   

      live    val    dur  acous   spch    pop  
0    False  False  False  False  False  False  
1    False  False  False  False  False  False  
2    False  False  False  False  False  False  
3    False  False  False  False  False  False  
4    False  False  False  False  False  False  
..     ...    ...    ...    ...    ...    ...  
598  False  False  False  False  False  False  
599  False  False  False  False  False  False  
600  False  False  False  False  False  False  
601  False  False  False  False  False  False  
602  False  False  False  False  False  False  

[603 rows x 15 columns]

In [ ]:
(df['artist'] == 'Queen').any()
# Nessa função aqui, eu tô questionando se a banda Queen está inserida em alguma parte do Data Frame

False

#OPERAÇÕES COM DATAFRAMES


In [ ]:
df_ops.head()
# mostrando o dataframe de novo

Unnamed: 0                 title         artist        top genre  year  \
0           1      Hey, Soul Sister          Train       neo mellow  2010   
1           2  Love The Way You Lie         Eminem  detroit hip hop  2010   
2           3               TiK ToK          Kesha        dance pop  2010   
3           4           Bad Romance      Lady Gaga        dance pop  2010   
5           6                  Baby  Justin Bieber     canadian pop  2010   

   bpm  nrgy  dnce  dB  live  val  dur  acous  spch  pop  
0   97    89    67  -4     8   80  217     19     4   83  
1   87    93    75  -5    52   64  263     24    23   82  
2  120    84    76  -3    29   71  200     10    14   80  
3  119    92    70  -4     8   71  295      0     4   79  
5   65    86    73  -5    11   54  214      4    14   77

In [ ]:
df_ops.drop(columns=['spch'], inplace=True)
# Dropei o " spch" da tabela/dataframe

<ipython-input-40-15891da2f0e1>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ops.drop(columns=['spch'], inplace=True)


In [ ]:
df_ops['dur'].mean()
#Trouxe a média matemática ( aritimética ) do " dur"

224.63698630136986

In [ ]:
df_ops['dur'].min()
#Trouxe o mínimo do Dur

134

In [ ]:
df_ops['dur'].max()
#Máximo do Dur

424

In [ ]:
df.agg({'acous':'mean','dur':'max'})
#trpuxe aqui a média do "acous" e a duração máxima , só que ao mesmo tempo

acous     14.3267
dur      424.0000
dtype: float64

In [ ]:
df_ops['dur'].cumsum()
#contando de forma incremental o "dur"

0         217
1         480
2         680
3         975
5        1189
        ...  
598    130292
599    130498
600    130758
601    130975
602    131188
Name: dur, Length: 584, dtype: int64

In [ ]:
df_ops.sort_values(by='dur', ascending = False)
# Ordenei pelo "duração", neste caso, concendi ao ascending o " false", ou seja, ele vai trazer do maior para o menor

Unnamed: 0                                              title  \
188         189                                                TKO   
422         423  Wish That You Were Here - From “Miss Peregrine...   
63           64                                            Monster   
162         163                             Lose Yourself to Dance   
194         195                                Take Back the Night   
..          ...                                                ...   
581         582         Good as Hell (feat. Ariana Grande) - Remix   
492         493          Reality (feat. Janieck Devy) - Radio Edit   
174         175                       I Love It (feat. Charli XCX)   
591         592                    All Around The World (La La La)   
330         331                                      Mark My Words   

                     artist     top genre  year  bpm  nrgy  dnce  dB  live  \
188       Justin Timberlake     dance pop  2013  138    68    61  -7    43   
422  Florence + The Machine       art pop  2016   94    57    37  -6    13   
63               Kanye West   chicago rap  2011  125    69    63  -6    67   
162               Daft Punk       electro  2013  100    66    83  -8     8   
194       Justin Timberlake     dance pop  2013  107    66    59  -5    64   
..                      ...           ...   ...  ...   ...   ...  ..   ...   
581                   Lizzo   escape room  2019   96    89    67  -3    74   
492        Lost Frequencies   belgian edm  2017  122    64    73  -7     8   
174               Icona Pop     candy pop  2013  126    91    71  -3    15   
591                   R3HAB      big room  2019  125    86    73  -5    11   
330           Justin Bieber  canadian pop  2015  114    26    38  -9    17   

     val  dur  acous  pop  
188   49  424      1   58  
422   12  403     72   57  
63    10  379      0   73  
162   67  354      8   72  
194   33  353      4   54  
..   ...  ...    ...  ...  
581   48  159     30   90  
492   53  158      2   59  
174   82  157      1   67  
591   52  148     48   82  
330   52  134     88   63  

[584 rows x 14 columns]

In [ ]:
df_ops.sort_values(by='dur', ascending = True)
# Fiz o mesmo de cima, só que ao contrário. Aqui tô trazendo do menor para o maior mesmo !


Unnamed: 0                                              title  \
330         331                                      Mark My Words   
591         592                    All Around The World (La La La)   
174         175                       I Love It (feat. Charli XCX)   
492         493          Reality (feat. Janieck Devy) - Radio Edit   
334         335                               Reality - Radio Edit   
..          ...                                                ...   
194         195                                Take Back the Night   
162         163                             Lose Yourself to Dance   
63           64                                            Monster   
422         423  Wish That You Were Here - From “Miss Peregrine...   
188         189                                                TKO   

                     artist     top genre  year  bpm  nrgy  dnce  dB  live  \
330           Justin Bieber  canadian pop  2015  114    26    38  -9    17   
591                   R3HAB      big room  2019  125    86    73  -5    11   
174               Icona Pop     candy pop  2013  126    91    71  -3    15   
492        Lost Frequencies   belgian edm  2017  122    64    73  -7     8   
334        Lost Frequencies   belgian edm  2015  122    70    71  -8     7   
..                      ...           ...   ...  ...   ...   ...  ..   ...   
194       Justin Timberlake     dance pop  2013  107    66    59  -5    64   
162               Daft Punk       electro  2013  100    66    83  -8     8   
63               Kanye West   chicago rap  2011  125    69    63  -6    67   
422  Florence + The Machine       art pop  2016   94    57    37  -6    13   
188       Justin Timberlake     dance pop  2013  138    68    61  -7    43   

     val  dur  acous  pop  
330   52  134     88   63  
591   52  148     48   82  
174   82  157      1   67  
492   53  158      2   59  
334   60  159      2   61  
..   ...  ...    ...  ...  
194   33  353      4   54  
162   67  354      8   72  
63    10  379      0   73  
422   12  403     72   57  
188   49  424      1   58  

[584 rows x 14 columns]

In [ ]:
df_ops['year'].astype(str)
# Converti o campo " ano " para string

0      2010
1      2010
2      2010
3      2010
5      2010
       ... 
598    2019
599    2019
600    2019
601    2019
602    2019
Name: year, Length: 584, dtype: object

In [ ]:
df_ops['year'].cumsum()


0         2010
1         4020
2         6030
3         8040
5        10050
        ...   
598    1168469
599    1170488
600    1172507
601    1174526
602    1176545
Name: year, Length: 584, dtype: int64

In [ ]:
pd.get_dummies(df_ops,columns=['artist'])
#Criei uma variável numa coluna para confirmar se a " música" pertence ao " artista"

Unnamed: 0                                              title  \
0             1                                   Hey, Soul Sister   
1             2                               Love The Way You Lie   
2             3                                            TiK ToK   
3             4                                        Bad Romance   
5             6                                               Baby   
..          ...                                                ...   
598         599                Find U Again (feat. Camila Cabello)   
599         600      Cross Me (feat. Chance the Rapper & PnB Rock)   
600         601  No Brainer (feat. Justin Bieber, Chance the Ra...   
601         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
602         603                                   Kills You Slowly   

           top genre  year  bpm  nrgy  dnce  dB  live  val  ...  artist_Train  \
0         neo mellow  2010   97    89    67  -4     8   80  ...             1   
1    detroit hip hop  2010   87    93    75  -5    52   64  ...             0   
2          dance pop  2010  120    84    76  -3    29   71  ...             0   
3          dance pop  2010  119    92    70  -4     8   71  ...             0   
5       canadian pop  2010   65    86    73  -5    11   54  ...             0   
..               ...   ...  ...   ...   ...  ..   ...  ...  ...           ...   
598        dance pop  2019  104    66    61  -7    20   16  ...             0   
599              pop  2019   95    79    75  -6     7   61  ...             0   
600        dance pop  2019  136    76    53  -5     9   65  ...             0   
601        dance pop  2019  114    79    60  -6    42   24  ...             0   
602       electropop  2019  150    44    70  -9    13   23  ...             0   

     artist_Troye Sivan  artist_Usher  artist_Wiz Khalifa  \
0                     0             0                   0   
1                     0             0                   0   
2                     0             0                   0   
3                     0             0                   0   
5                     0             0                   0   
..                  ...           ...                 ...   
598                   0             0                   0   
599                   0             0                   0   
600                   0             0                   0   
601                   0             0                   0   
602                   0             0                   0   

     artist_Years & Years  artist_ZAYN  artist_Zara Larsson  artist_Zedd  \
0                       0            0                    0            0   
1                       0            0                    0            0   
2                       0            0                    0            0   
3                       0            0                    0            0   
5                       0            0                    0            0   
..                    ...          ...                  ...          ...   
598                     0            0                    0            0   
599                     0            0                    0            0   
600                     0            0                    0            0   
601                     0            0                    0            0   
602                     0            0                    0            0   

     artist_fun.  artist_will.i.am  
0              0                 0  
1              0                 0  
2              0                 0  
3              0                 0  
5              0                 0  
..           ...               ...  
598            0                 0  
599            0                 0  
600            0                 0  
601            0                 0  
602            0                 0  

[584 rows x 195 columns]

In [ ]:
df_ops.assign(energy_dance= lambda df: df['dnce']*df['nrgy'])
#usei o assign para criar um novo campo onde, eu multiplico o dnce pelo nrgy

Unnamed: 0                                              title  \
0             1                                   Hey, Soul Sister   
1             2                               Love The Way You Lie   
2             3                                            TiK ToK   
3             4                                        Bad Romance   
5             6                                               Baby   
..          ...                                                ...   
598         599                Find U Again (feat. Camila Cabello)   
599         600      Cross Me (feat. Chance the Rapper & PnB Rock)   
600         601  No Brainer (feat. Justin Bieber, Chance the Ra...   
601         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
602         603                                   Kills You Slowly   

               artist        top genre  year  bpm  nrgy  dnce  dB  live  val  \
0               Train       neo mellow  2010   97    89    67  -4     8   80   
1              Eminem  detroit hip hop  2010   87    93    75  -5    52   64   
2               Kesha        dance pop  2010  120    84    76  -3    29   71   
3           Lady Gaga        dance pop  2010  119    92    70  -4     8   71   
5       Justin Bieber     canadian pop  2010   65    86    73  -5    11   54   
..                ...              ...   ...  ...   ...   ...  ..   ...  ...   
598       Mark Ronson        dance pop  2019  104    66    61  -7    20   16   
599        Ed Sheeran              pop  2019   95    79    75  -6     7   61   
600         DJ Khaled        dance pop  2019  136    76    53  -5     9   65   
601       Mark Ronson        dance pop  2019  114    79    60  -6    42   24   
602  The Chainsmokers       electropop  2019  150    44    70  -9    13   23   

     dur  acous  pop  energy_dance  
0    217     19   83          5963  
1    263     24   82          6975  
2    200     10   80          6384  
3    295      0   79          6440  
5    214      4   77          6278  
..   ...    ...  ...           ...  
598  176      1   75          4026  
599  206     21   75          5925  
600  260      7   70          4028  
601  217      1   69          4740  
602  213      6   67          3080  

[584 rows x 15 columns]

#GROUP BY  DFs
Ou seja...  fundindo os dfs !


In [ ]:
df_ops.T

0                     1          2            3    \
Unnamed: 0                 1                     2          3            4   
title       Hey, Soul Sister  Love The Way You Lie    TiK ToK  Bad Romance   
artist                 Train                Eminem      Kesha    Lady Gaga   
top genre         neo mellow       detroit hip hop  dance pop    dance pop   
year                    2010                  2010       2010         2010   
bpm                       97                    87        120          119   
nrgy                      89                    93         84           92   
dnce                      67                    75         76           70   
dB                        -4                    -5         -3           -4   
live                       8                    52         29            8   
val                       80                    64         71           71   
dur                      217                   263        200          295   
acous                     19                    24         10            0   
pop                       83                    82         80           79   

                      5          6            7    \
Unnamed: 0              6          7            8   
title                Baby   Dynamite      Secrets   
artist      Justin Bieber  Taio Cruz  OneRepublic   
top genre    canadian pop  dance pop    dance pop   
year                 2010       2010         2010   
bpm                    65        120          148   
nrgy                   86         78           76   
dnce                   73         75           52   
dB                     -5         -4           -6   
live                   11          4           12   
val                    54         82           38   
dur                   214        203          225   
acous                   4          0            7   
pop                    77         77           77   

                                                   8    \
Unnamed: 0                                           9   
title       Empire State of Mind (Part II) Broken Down   
artist                                     Alicia Keys   
top genre                                      hip pop   
year                                              2010   
bpm                                                 93   
nrgy                                                37   
dnce                                                48   
dB                                                  -8   
live                                                12   
val                                                 14   
dur                                                216   
acous                                               74   
pop                                                 76   

                                 9    \
Unnamed: 0                        10   
title       Only Girl (In The World)   
artist                       Rihanna   
top genre              barbadian pop   
year                            2010   
bpm                              126   
nrgy                              72   
dnce                              79   
dB                                -4   
live                               7   
val                               61   
dur                              235   
acous                             13   
pop                               73   

                                                  10   ...               593  \
Unnamed: 0                                         11  ...               594   
title       Club Can't Handle Me (feat. David Guetta)  ...     Call You Mine   
artist                                       Flo Rida  ...  The Chainsmokers   
top genre                                   dance pop  ...        electropop   
year                                             2010  ...              2019   
bpm                                               128  ...               104   
nrgy                      

In [ ]:
df_ops.head()

Unnamed: 0                 title         artist        top genre  year  \
0           1      Hey, Soul Sister          Train       neo mellow  2010   
1           2  Love The Way You Lie         Eminem  detroit hip hop  2010   
2           3               TiK ToK          Kesha        dance pop  2010   
3           4           Bad Romance      Lady Gaga        dance pop  2010   
5           6                  Baby  Justin Bieber     canadian pop  2010   

   bpm  nrgy  dnce  dB  live  val  dur  acous  pop  
0   97    89    67  -4     8   80  217     19   83  
1   87    93    75  -5    52   64  263     24   82  
2  120    84    76  -3    29   71  200     10   80  
3  119    92    70  -4     8   71  295      0   79  
5   65    86    73  -5    11   54  214      4   77

In [ ]:
df.groupby('artist').count()

Unnamed: 0  title  top genre  year  bpm  nrgy  dnce  dB  \
artist                                                                         
3OH!3                         1      1          1     1    1     1     1   1   
5 Seconds of Summer           1      1          1     1    1     1     1   1   
A Great Big World             1      1          1     1    1     1     1   1   
Adam Lambert                  2      2          2     2    2     2     2   2   
Adele                        10     10         10    10   10    10    10  10   
...                         ...    ...        ...   ...  ...   ...   ...  ..   
ZAYN                          5      5          5     5    5     5     5   5   
Zara Larsson                  1      1          1     1    1     1     1   1   
Zedd                          6      6          6     6    6     6     6   6   
fun.                          2      2          2     2    2     2     2   2   
will.i.am                     1      1          1     1    1     1     1   1   

                     live  val  dur  acous  spch  pop  
artist                                                 
3OH!3                   1    1    1      1     1    1  
5 Seconds of Summer     1    1    1      1     1    1  
A Great Big World       1    1    1      1     1    1  
Adam Lambert            2    2    2      2     2    2  
Adele                  10   10   10     10    10   10  
...                   ...  ...  ...    ...   ...  ...  
ZAYN                    5    5    5      5     5    5  
Zara Larsson            1    1    1      1     1    1  
Zedd                    6    6    6      6     6    6  
fun.                    2    2    2      2     2    2  
will.i.am               1    1    1      1     1    1  

[184 rows x 14 columns]

In [ ]:
df.groupby('artist')['title'].count()

artist
3OH!3                   1
5 Seconds of Summer     1
A Great Big World       1
Adam Lambert            2
Adele                  10
                       ..
ZAYN                    5
Zara Larsson            1
Zedd                    6
fun.                    2
will.i.am               1
Name: title, Length: 184, dtype: int64

In [ ]:
df.groupby(['artist','year'])['title'].count()

artist               year
3OH!3                2010    1
5 Seconds of Summer  2014    1
A Great Big World    2014    1
Adam Lambert         2010    2
Adele                2011    2
                            ..
Zedd                 2015    1
                     2016    1
                     2017    2
fun.                 2012    2
will.i.am            2013    1
Name: title, Length: 409, dtype: int64

In [ ]:
df.groupby(['artist','year']).agg({'year':'count','dur':'mean'})

year    dur
artist              year             
3OH!3               2010     1  192.0
5 Seconds of Summer 2014     1  202.0
A Great Big World   2014     1  229.0
Adam Lambert        2010     2  227.5
Adele               2011     2  256.5
...                        ...    ...
Zedd                2015     1  240.0
                    2016     1  225.0
                    2017     2  207.5
fun.                2012     2  264.0
will.i.am           2013     1  280.0

[409 rows x 2 columns]

In [ ]:
df_groupedyear= df.groupby('year')

In [ ]:
df_groupedyear.ngroups

10

In [ ]:
df_groupedyear.groups

{2010: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50], 2011: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103], 2012: [104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138], 2013: [139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209], 2014: [210, 211, 212, 213, 

In [ ]:
df_groupedyear.size()

year
2010    51
2011    53
2012    35
2013    71
2014    58
2015    95
2016    80
2017    65
2018    64
2019    31
dtype: int64

In [ ]:
df_groupedyear.get_group(2014)

Unnamed: 0                                              title  \
210         211                                          All of Me   
211         212                                       Stay With Me   
212         213                                             Summer   
213         214                     Happy - From "Despicable Me 2"   
214         215                                               Rude   
215         216                                       Shake It Off   
216         217                                         Dark Horse   
217         218                                        Hey Brother   
218         219                                               Maps   
219         220                                           Treasure   
220         221                                         Let Her Go   
221         222                                            Problem   
222         223                                            Pompeii   
223         224                                               Team   
224         225                                      Love Me Again   
225         226                                              Latch   
226         227                                          Adore You   
227         228                            Love Never Felt So Good   
228         229                                               Burn   
229         230                               She Looks So Perfect   
230         231                                              Fancy   
231         232                        Talk Dirty (feat. 2 Chainz)   
232         233                                            Gorilla   
233         234                                              human   
234         235                                        Young Girls   
235         236                          Wiggle (feat. Snoop Dogg)   
236         237                                      Love Runs Out   
237         238                                  This Is How We Do   
238         239                           Mmm Yeah (feat. Pitbull)   
239         240    A Little Party Never Killed Nobody (All We Got)   
240         241                                            #SELFIE   
241         242                                          Partition   
242         243                                           Birthday   
243         244                                             G.U.Y.   
244         245  Stay The Night - Featuring Hayley Williams Of ...   
245         246          Let It Go - From "Frozen / Single Version   
246         247                                              Wings   
247         248       Can't Remember to Forget You (feat. Rihanna)   
248         249      Shot Me Down (feat. Skylar Grey) - Radio Edit   
249         250                                      Say Something   
250         251                                A Sky Full of Stars   
251         252                                    Come Get It Bae   
252         253                                         Chandelier   
253         254                                                 XO   
254         255  We Are One (Ole Ola) [The Official 2014 FIFA W...   
255         256                                   Not About Angels   
256         257                                      Drunk in Love   
257         258                                           Anaconda   
258         259  Boom Clap - From the Motion Picture Das Schick...   
259         260     La La La (Brasil 2014) (feat. Carlinhos Brown)   
260         261                     Tee Shirt - Soundtrack Version   
261         262                                   Words as Weapons   
262         263                              You're Mine (Eternal)   
263         264                                            Sheezus   
264         265                                         Cannonball   
265         266                    It's On Again - Main Soundtrack   
266         267

# MERGIAR O DATASET
- O join  - O join combina os dataframes com base no index
- O merge - O Merge combina os dataframes quando você indica as colunas
- O appending - Quando você " cola " um dataframe embaixo do outro

In [ ]:
df.merge(dfs,left_on='artist',right_on='Artists',how='left').fillna(0)

Unnamed: 0                                              title  \
0              1                                   Hey, Soul Sister   
1              2                               Love The Way You Lie   
2              3                                            TiK ToK   
3              4                                        Bad Romance   
4              5                               Just the Way You Are   
...          ...                                                ...   
1858         599                Find U Again (feat. Camila Cabello)   
1859         600      Cross Me (feat. Chance the Rapper & PnB Rock)   
1860         601  No Brainer (feat. Justin Bieber, Chance the Ra...   
1861         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
1862         603                                   Kills You Slowly   

                artist        top genre  year  bpm  nrgy  dnce  dB  live  ...  \
0                Train       neo mellow  2010   97    89    67  -4     8  ...   
1               Eminem  detroit hip hop  2010   87    93    75  -5    52  ...   
2                Kesha        dance pop  2010  120    84    76  -3    29  ...   
3            Lady Gaga        dance pop  2010  119    92    70  -4     8  ...   
4           Bruno Mars              pop  2010  109    84    64  -5     9  ...   
...                ...              ...   ...  ...   ...   ...  ..   ...  ...   
1858       Mark Ronson        dance pop  2019  104    66    61  -7    20  ...   
1859        Ed Sheeran              pop  2019   95    79    75  -6     7  ...   
1860         DJ Khaled        dance pop  2019  136    76    53  -5     9  ...   
1861       Mark Ronson        dance pop  2019  114    79    60  -6    42  ...   
1862  The Chainsmokers       electropop  2019  150    44    70  -9    13  ...   

      spch  pop  Country  Continent  Rank Title Artists  Album Explicit  \
0        4   83        0          0   0.0     0       0      0      0.0   
1       23   82        0          0   0.0     0       0      0      0.0   
2       14   80        0          0   0.0     0       0      0      0.0   
3        4   79        0          0   0.0     0       0      0      0.0   
4        4   78        0          0   0.0     0       0      0      0.0   
...    ...  ...      ...        ...   ...   ...     ...    ...      ...   
1858     3   75        0          0   0.0     0       0      0      0.0   
1859    12   75        0          0   0.0     0       0      0      0.0   
1860    34   70        0          0   0.0     0       0      0      0.0   
1861     7   69        0          0   0.0     0       0      0      0.0   
1862     6   67        0          0   0.0     0       0      0      0.0   

     Duration  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1858        0  
1859        0  
1860        0  
1861        0  
1862        0  

[1863 rows x 23 columns]

In [ ]:
df.merge(dfs,left_on='artist',right_on='Artists',how='left', indicator=True).fillna(0)

Unnamed: 0                                              title  \
0              1                                   Hey, Soul Sister   
1              2                               Love The Way You Lie   
2              3                                            TiK ToK   
3              4                                        Bad Romance   
4              5                               Just the Way You Are   
...          ...                                                ...   
1858         599                Find U Again (feat. Camila Cabello)   
1859         600      Cross Me (feat. Chance the Rapper & PnB Rock)   
1860         601  No Brainer (feat. Justin Bieber, Chance the Ra...   
1861         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
1862         603                                   Kills You Slowly   

                artist        top genre  year  bpm  nrgy  dnce  dB  live  ...  \
0                Train       neo mellow  2010   97    89    67  -4     8  ...   
1               Eminem  detroit hip hop  2010   87    93    75  -5    52  ...   
2                Kesha        dance pop  2010  120    84    76  -3    29  ...   
3            Lady Gaga        dance pop  2010  119    92    70  -4     8  ...   
4           Bruno Mars              pop  2010  109    84    64  -5     9  ...   
...                ...              ...   ...  ...   ...   ...  ..   ...  ...   
1858       Mark Ronson        dance pop  2019  104    66    61  -7    20  ...   
1859        Ed Sheeran              pop  2019   95    79    75  -6     7  ...   
1860         DJ Khaled        dance pop  2019  136    76    53  -5     9  ...   
1861       Mark Ronson        dance pop  2019  114    79    60  -6    42  ...   
1862  The Chainsmokers       electropop  2019  150    44    70  -9    13  ...   

      pop  Country  Continent  Rank  Title Artists Album  Explicit Duration  \
0      83        0          0   0.0      0       0     0       0.0        0   
1      82        0          0   0.0      0       0     0       0.0        0   
2      80        0          0   0.0      0       0     0       0.0        0   
3      79        0          0   0.0      0       0     0       0.0        0   
4      78        0          0   0.0      0       0     0       0.0        0   
...   ...      ...        ...   ...    ...     ...   ...       ...      ...   
1858   75        0          0   0.0      0       0     0       0.0        0   
1859   75        0          0   0.0      0       0     0       0.0        0   
1860   70        0          0   0.0      0       0     0       0.0        0   
1861   69        0          0   0.0      0       0     0       0.0        0   
1862   67        0          0   0.0      0       0     0       0.0        0   

         _merge  
0     left_only  
1     left_only  
2     left_only  
3     left_only  
4     left_only  
...         ...  
1858  left_only  
1859  left_only  
1860  left_only  
1861  left_only  
1862  left_only  

[1863 rows x 24 columns]

In [ ]:
df.join(dfs)

Unnamed: 0                                              title  \
0             1                                   Hey, Soul Sister   
1             2                               Love The Way You Lie   
2             3                                            TiK ToK   
3             4                                        Bad Romance   
4             5                               Just the Way You Are   
..          ...                                                ...   
598         599                Find U Again (feat. Camila Cabello)   
599         600      Cross Me (feat. Chance the Rapper & PnB Rock)   
600         601  No Brainer (feat. Justin Bieber, Chance the Ra...   
601         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
602         603                                   Kills You Slowly   

               artist        top genre  year  bpm  nrgy  dnce  dB  live  ...  \
0               Train       neo mellow  2010   97    89    67  -4     8  ...   
1              Eminem  detroit hip hop  2010   87    93    75  -5    52  ...   
2               Kesha        dance pop  2010  120    84    76  -3    29  ...   
3           Lady Gaga        dance pop  2010  119    92    70  -4     8  ...   
4          Bruno Mars              pop  2010  109    84    64  -5     9  ...   
..                ...              ...   ...  ...   ...   ...  ..   ...  ...   
598       Mark Ronson        dance pop  2019  104    66    61  -7    20  ...   
599        Ed Sheeran              pop  2019   95    79    75  -6     7  ...   
600         DJ Khaled        dance pop  2019  136    76    53  -5     9  ...   
601       Mark Ronson        dance pop  2019  114    79    60  -6    42  ...   
602  The Chainsmokers       electropop  2019  150    44    70  -9    13  ...   

     spch  pop         Country      Continent  Rank  \
0       4   83          Global         Global     1   
1      23   82          Global         Global     2   
2      14   80          Global         Global     3   
3       4   79          Global         Global     4   
4       4   78          Global         Global     5   
..    ...  ...             ...            ...   ...   
598     3   75      Costa Rica  North America    49   
599    12   75      Costa Rica  North America    50   
600    34   70  Czech Republic         Europe     1   
601     7   69  Czech Republic         Europe     2   
602     6   67  Czech Republic         Europe     3   

                               Title                   Artists  \
0    Rain On Me (with Ariana Grande)  Lady Gaga, Ariana Grande   
1                    Blinding Lights                The Weeknd   
2       ROCKSTAR (feat. Roddy Ricch)       DaBaby, Roddy Ricch   
3              Roses - Imanbek Remix        SAINt JHN, Imanbek   
4                       Toosie Slide                     Drake   
..                               ...                       ...   
598                          The Box               Roddy Ricch   
599               CANCIÓN CON YANDEL         Yandel, Bad Bunny   
600                  Blinding Lights                The Weeknd   
601            Roses - Imanbek Remix        SAINt JHN, Imanbek   
602                            GOOBA                   6ix9ine   

                                     Album Explicit Duration  
0          Rain On Me (with Ariana Grande)        0     3:02  
1                              After Hours        0     3:20  
2                         BLAME IT ON BABY        1     3:01  
3                    Roses (Imanbek Remix)        1     2:56  
4                     Dark Lane Demo Tapes        1     4:07  
..                                     ...      ...      ...  
598  Please Excuse Me For Being Antisocial        1     3:16  
599                LAS QUE NO IBAN A SALIR        1     3:29  
600                            After Hours        0     3:20  
601                  Roses (Imanbek Remix)        1     2:56  
602                                  GOOBA        1     

In [ ]:
df.append(dfs).fillna('hehe')

<ipython-input-69-f2f5816b5c08>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(dfs).fillna('hehe')


Unnamed: 0                 title      artist        top genre    year  \
0           1.0      Hey, Soul Sister       Train       neo mellow  2010.0   
1           2.0  Love The Way You Lie      Eminem  detroit hip hop  2010.0   
2           3.0               TiK ToK       Kesha        dance pop  2010.0   
3           4.0           Bad Romance   Lady Gaga        dance pop  2010.0   
4           5.0  Just the Way You Are  Bruno Mars              pop  2010.0   
...         ...                   ...         ...              ...     ...   
3145       hehe                  hehe        hehe             hehe    hehe   
3146       hehe                  hehe        hehe             hehe    hehe   
3147       hehe                  hehe        hehe             hehe    hehe   
3148       hehe                  hehe        hehe             hehe    hehe   
3149       hehe                  hehe        hehe             hehe    hehe   

        bpm  nrgy  dnce    dB  live  ...  spch   pop  Country Continent  Rank  \
0      97.0  89.0  67.0  -4.0   8.0  ...   4.0  83.0     hehe      hehe  hehe   
1      87.0  93.0  75.0  -5.0  52.0  ...  23.0  82.0     hehe      hehe  hehe   
2     120.0  84.0  76.0  -3.0  29.0  ...  14.0  80.0     hehe      hehe  hehe   
3     119.0  92.0  70.0  -4.0   8.0  ...   4.0  79.0     hehe      hehe  hehe   
4     109.0  84.0  64.0  -5.0   9.0  ...   4.0  78.0     hehe      hehe  hehe   
...     ...   ...   ...   ...   ...  ...   ...   ...      ...       ...   ...   
3145   hehe  hehe  hehe  hehe  hehe  ...  hehe  hehe  Vietnam      Asia  46.0   
3146   hehe  hehe  hehe  hehe  hehe  ...  hehe  hehe  Vietnam      Asia  47.0   
3147   hehe  hehe  hehe  hehe  hehe  ...  hehe  hehe  Vietnam      Asia  48.0   
3148   hehe  hehe  hehe  hehe  hehe  ...  hehe  hehe  Vietnam      Asia  49.0   
3149   hehe  hehe  hehe  hehe  hehe  ...  hehe  hehe  Vietnam      Asia  50.0   

                  Title                     Artists              Album  \
0                  hehe                        hehe               hehe   
1                  hehe                        hehe               hehe   
2                  hehe                        hehe               hehe   
3                  hehe                        hehe               hehe   
4                  hehe                        hehe               hehe   
...                 ...                         ...                ...   
3145         ĐÃ TỪNG LÀ                         Vũ.         ĐÃ TỪNG LÀ   
3146  Mượn Rượu Tỏ Tình             BigDaddy, Emily  Mượn Rượu Tỏ Tình   
3147       Ngày Tận Thế  Tóc Tiên, Da LAB, Touliver       Ngày Tận Thế   
3148       Đi Đu Đưa Đi                 Bich Phuong       Đi Đu Đưa Đi   
3149    Blinding Lights                  The Weeknd        After Hours   

     Explicit Duration  
0        hehe     hehe  
1        hehe     hehe  
2        hehe     hehe  
3        hehe     hehe  
4        hehe     hehe  
...       ...      ...  
3145      0.0     4:20  
3146      0.0     3:18  
3147      0.0     3:52  
3148      0.0     3:40  
3149      0.0     3:20  

[3753 rows x 23 columns]

In [ ]:
df_grouped=df.groupby('artist')['title'].count()

In [ ]:
df_grouped=df_grouped.reset_index()

In [ ]:
df[:10].style.background_gradient(axis=0)

In [ ]:
df[:15].style.text_gradient(low=0.75,high=1.3)

###AGORA É HORA DE COMEÇAR O NUMPY ! :))))
---
Numpy é uma biblioteca do Python que trabalha e opera vetores/Arrays.
Arrays unidimensionais, bidimensionais e até mesmo tridimensionais ou com mais dimensões.
Muito mais rápido que os outros tipos de dados do python. até 10x mais rápido, facilidade para encontrar os dados, melhor alocação de memória *usa menos* !



In [ ]:
import numpy as np
#importando o Numpy


In [ ]:
vetor_linha=np.array([1,2,3,4,5])
#criando uma variável chamada vetor_linha e atribuindo alguns valores a ela

In [ ]:
print(vetor_linha)

[1 2 3 4 5]


In [ ]:
vetor_coluna=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#Criando uma var chamada vetor_coluna e colocando dados dentro dela ( primeira matriz de vdd)

In [ ]:
print(vetor_coluna)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
matriz = np.array([[14,62,3],[6,4,8],[12,65,78]])
#fiz a mesma coisa de cima


In [ ]:
print(matriz)

[[14 62  3]
 [ 6  4  8]
 [12 65 78]]


In [ ]:
np.linspace(0,20,num=5)
#linspace vai criar um vetor ( array) e vai preencher ele baseado nas coisas que você definiu

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.random.randint(0,11,3)
#Criando vetor randômico de 0 a 11, com três elementos

array([7, 0, 7])

In [ ]:
print(matriz.shape)
#mostrando o shape da matriz

(3, 3)


In [ ]:
print(matriz.dtype)
#Tipo de dados da matriz

int64


In [ ]:
print(matriz.size)
#quantidade de elementos dentro da matriz

9


In [ ]:
print(matriz.ndim)
#Número de dimensões

2


In [ ]:
print(np.min(matriz))
#menor número dentro da matriz

3


In [ ]:
print(np.max(matriz))
#Maior número dentro da matriz

78


In [ ]:
print(np.max(matriz,axis=0))
#exibir maiores números de cada uma das colunas

[14 65 78]


In [ ]:
print(np.min(matriz,axis=1))
#menor valor de cad auma das colunas


[ 3  4 12]


In [ ]:
a = np.arange(6)

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
#Reshape as - Mudança de formato - De array to matriz
b = a.reshape(3,2)

In [ ]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
#basic array creation
s=np.array([1,9,15,4])

In [ ]:
print(s)

[ 1  9 15  4]


In [ ]:
np.sort(s)

array([ 1,  4,  9, 15])

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
print(s)

[ 1  9 15  4]


In [ ]:
#concatenate
t = np.concatenate((a,s))

In [ ]:
#Sort/organize  - nesse caso aqui, em função da ordem crescente
np.sort(t)

array([ 0,  1,  1,  2,  3,  4,  4,  5,  9, 15])

# Operações matemáticas

In [ ]:
#Desvio padrão ( em função da matriz)
np.std(matriz)

28.986586936412884

In [ ]:
#pERCENTIL EM FUNÇÃO DE 10
np.percentile(a,10)

0.5

In [ ]:
#variança
np.var(matriz)

840.2222222222222

In [ ]:
#matriz transposta
matriz.T

array([[14,  6, 12],
       [62,  4, 65],
       [ 3,  8, 78]])

In [ ]:
print(matriz)

[[14 62  3]
 [ 6  4  8]
 [12 65 78]]


#Operações com Matrizes

In [ ]:
matriz1= np.array([[14,2,3],[48,6,8]])

In [ ]:
matriz2=np.array([[1,21,3],[4,54,66]])

In [ ]:
print(matriz1)

[[14  2  3]
 [48  6  8]]


In [ ]:
print(matriz2)

[[ 1 21  3]
 [ 4 54 66]]


In [ ]:
#Soma de matrizes
print(np.add(matriz1,matriz2))

[[15 23  6]
 [52 60 74]]


In [ ]:
#Subtração de matrizes

print(np.subtract(matriz1,matriz2))

[[ 13 -19   0]
 [ 44 -48 -58]]


In [ ]:
#Multiplicação
print(np.multiply(matriz1,matriz2))
#ou eu posso usar apenas operadores aritiméticos simples


[[ 14  42   9]
 [192 324 528]]


In [ ]:
#Calculos diagonais -


In [ ]:
#Diagonal principal
print(matriz1.diagonal())

[14  6]


In [ ]:
print(matriz1.diagonal(offset=1))

[2 8]


In [ ]:
print(matriz1.diagonal(offset=-1))

[48]


##MATRIZ INVERSA

In [ ]:
print(matriz)

[[14 62  3]
 [ 6  4  8]
 [12 65 78]]


In [ ]:
#matriz inversa
print(np.linalg.inv(matriz))

[[ 0.00833667  0.18601202 -0.0193988 ]
 [ 0.01490982 -0.04232465  0.00376754]
 [-0.01370741  0.00665331  0.01266533]]


#Adição e remoção de elementos ao Array/matriz


In [ ]:
#Criar uma função
add_100=lambda i:i+100

In [ ]:
# Criar o objeto de adição ( para fazer a função funcionar ) _add_100=np.vectorize(add_100)

In [ ]:
#Código inútil xD ---

print(_add_100)

In [ ]:
#Printar o objeto sendo adicionado a matriz !
print(_add_100(matriz))

[[114 162 103]
 [106 104 108]
 [112 165 178]]


#Operações lógicas com arrays


In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:

print(np.where(a<4))

(array([0, 1, 2, 3]),)


In [ ]:
print(np.where(a>2))

(array([3, 4, 5]),)


In [ ]:
print(np.where(a!=2))

(array([0, 1, 3, 4, 5]),)


In [ ]:
print(np.where(a==3))

(array([3]),)


In [ ]:
print(np.where((a>2)&(a!=3)))

(array([4, 5]),)


In [ ]:
print(np.where((a>2)|(a!=3)))

(array([0, 1, 2, 3, 4, 5]),)
